#!/usr/bin/env python3
"""Extract the sketch's AUD1 TX functions verbatim for the native harness.

Why extraction and not a hand-written copy. The other firmware gates in this
directory (aud1_tx_gate.cpp) are parallel reimplementations, and
check-runtime-sync.sh exists precisely because hand-maintained copies drift and
leave every gate green while testing dead code. A copy of the TX ring and its
state machine would be the worst candidate for that: it is the code that decides
whether the radio keys and whether the transmission survives, and a drift there
would be invisible until it happened on the air.

So the harness compiles the real text. This script lifts the named functions out
of wifilt.ino by brace matching and writes them into one include file.
Reformat the sketch and the build fails loudly with the name it could not find,
which is the correct outcome -- never a silently stale test.
"""

import re
import sys
from pathlib import Path

# Order matters: the generated file is included as a single translation unit, so
# each function must appear after everything it calls (or be forward declared in
# the harness shim).
WANTED = [
    "String extractJsonString(const String &json, const char *key)",
    "bool extractJsonBool(const String &json, const char *key, bool defaultValue)",
    "static uint16_t aud1GetBE16(const uint8_t* p)",
    "static uint32_t aud1GetBE32(const uint8_t* p)",
    "static uint64_t aud1GetBE64(const uint8_t* p)",
    "static uint8_t aud1Pcm16ToUlaw(int16_t input)",
    # Lifted, not stubbed, for the reason the whole harness exists: which ALC
    # source these pick is the difference between a working calibration and one
    # that reports "the radio never answered" about a radio that answered every
    # time. A harness copy of that choice would be the bug's hiding place.
    "static uint32_t aud1AlcRaw()",
    "static uint32_t aud1AlcSeq()",
    "static void aud1AlcReset()",
    "static void aud1TxResetState(Aud1TxState next = AUD1_TX_IDLE)",
    # aud1TxDiag() used to be lifted here for the same reason -- it was what the
    # operator read after a lost transmission. It no longer exists in the
    # sketch, and because nothing re-ran this harness after it went, the
    # extraction has been failing ever since: the fragility did its job, but
    # only into a terminal nobody was watching.
    "void aud1TxAbort(const String& reason, bool notify)",
    "void aud1TxTick(bool deferPrebufferMiss)",
    "static uint64_t aud1JsonU64(const String& json, const char* key)",
    "static void aud1HandleControl(const String& json)",
    "static bool aud1AcceptTxPacket(const uint8_t* wire, size_t length)",
]


def extract(text: str, signature: str) -> str:
    """Return the whole definition, from the signature line to its closing brace."""
    start = text.find("\n" + signature)
    if start < 0:
        raise SystemExit(
            f"ERROR: cannot find in the sketch:\n  {signature}\n"
            "The sketch changed. Re-check the harness against the new code, then "
            "update WANTED in extract_sketch_aud1.py."
        )
    start += 1
    brace = text.find("{", start)
    if brace < 0:
        raise SystemExit(f"ERROR: no body for {signature}")
    depth, index, in_string, in_char, in_line_comment, in_block = 0, brace, False, False, False, False
    while index < len(text):
        char = text[index]
        pair = text[index:index + 2]
        if in_line_comment:
            if char == "\n":
                in_line_comment = False
        elif in_block:
            if pair == "*/":
                in_block = False
                index += 1
        elif in_string:
            if char == "\\":
                index += 1
            elif char == '"':
                in_string = False
        elif in_char:
            if char == "\\":
                index += 1
            elif char == "'":
                in_char = False
        elif pair == "//":
            in_line_comment = True
            index += 1
        elif pair == "/*":
            in_block = True
            index += 1
        elif char == '"':
            in_string = True
        elif char == "'":
            in_char = True
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start:index + 1]
        index += 1
    raise SystemExit(f"ERROR: unterminated body for {signature}")


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: extract_sketch_aud1.py <sketch.ino> <out.inc>")
    sketch = Path(sys.argv[1]).read_text(encoding="utf-8", errors="strict")
    parts = [
        "// GENERATED by prototype/js8-core-prototype/firmware/extract_sketch_aud1.py",
        "// Verbatim text from wifilt.ino. Do not edit; do not commit.",
        "",
    ]
    for signature in WANTED:
        body = extract(sketch, signature)
        parts.append(f"// ---- {signature} " + "-" * max(0, 60 - len(signature)))
        parts.append(body)
        parts.append("")

    generated = "\n".join(parts)

    # Cheap guards that the right code came across, so a future refactor that
    # keeps the signatures but guts the bodies still trips the build.
    for anchor in ["AUD1_TX_RING_SIZE", "unattendedMayKey", "audioPttOn()",
                   "aud1Pcm16ToUlaw(pcm)", "audioTxSnapshot",
                   "startAudioTx", "queueAudioTx"]:
        if anchor not in generated:
            raise SystemExit(
                f"ERROR: extracted text lacks {anchor!r}; the sketch's TX path "
                "changed shape and the harness must be re-checked."
            )

    Path(sys.argv[2]).write_text(generated, encoding="utf-8")
    lines = generated.count("\n")
    print(f"    extracted {len(WANTED)} functions, {lines} lines")


if __name__ == "__main__":
    main()
