#!/usr/bin/env python3
"""Lift named functions out of the sketch verbatim, signatures given on argv.

Same discipline and the same brace matcher as extract_sketch_aud1.py, but without
a hardcoded list, so a small harness can ask for the two or three functions it
actually tests instead of pulling in the whole AUD1 TX path.

Deliberately fragile: a renamed or reformatted signature fails the build with the
text it could not find. A harness that silently tests a stale copy of firmware is
worse than no harness -- see the header of extract_sketch_aud1.py.

usage: extract_sketch_functions.py <sketch.ino> <out.inc> <signature> [...]
"""

import sys
from pathlib import Path


def extract(text: str, signature: str) -> str:
    """Return the whole definition, from the signature line to its closing brace."""
    start = text.find("\n" + signature)
    if start < 0:
        raise SystemExit(
            f"ERROR: cannot find in the sketch:\n  {signature}\n"
            "The sketch changed. Re-check the harness against the new code, then "
            "update the signature the build script passes in."
        )
    start += 1
    brace = text.find("{", start)
    if brace < 0:
        raise SystemExit(f"ERROR: no body for {signature}")
    depth, index = 0, brace
    in_string = in_char = in_line_comment = in_block = False
    while index < len(text):
        char = text[index]
        pair = text[index:index + 2]
        if in_line_comment:
            if char == "\n":
                in_line_comment = False
        elif in_block:
            if pair == "*/":
                in_block = False
                index += 1
        elif in_string:
            if char == "\\":
                index += 1
            elif char == '"':
                in_string = False
        elif in_char:
            if char == "\\":
                index += 1
            elif char == "'":
                in_char = False
        elif pair == "//":
            in_line_comment = True
            index += 1
        elif pair == "/*":
            in_block = True
            index += 1
        elif char == '"':
            in_string = True
        elif char == "'":
            in_char = True
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start:index + 1]
        index += 1
    raise SystemExit(f"ERROR: unterminated body for {signature}")


def main() -> None:
    if len(sys.argv) < 4:
        raise SystemExit(
            "usage: extract_sketch_functions.py <sketch.ino> <out.inc> <signature> [...]")
    sketch = Path(sys.argv[1]).read_text(encoding="utf-8", errors="strict")
    parts = [
        "// GENERATED by prototype/js8-core-prototype/firmware/extract_sketch_functions.py",
        "// Verbatim text from the sketch. Do not edit; do not commit.",
        "",
    ]
    for signature in sys.argv[3:]:
        parts.append(f"// ---- {signature} " + "-" * max(0, 60 - len(signature)))
        parts.append(extract(sketch, signature))
        parts.append("")
    Path(sys.argv[2]).write_text("\n".join(parts), encoding="utf-8")
    print(f"    {len(sys.argv) - 3} function(s) -> {sys.argv[2]}")


if __name__ == "__main__":
    main()
